reordered buttons
alexadonov/SoftwareStudio2A pull request #16
Opened 2020-05-13 04:21 UTC by jasmine-nahrain

+ cleaned up code

2020-05-13 10:14 UTC, jsaji requested changes
Solid work - just need to switch the rows of buttons (i.e. "load", "save", etc put on top, and "add wire", "undo", "redo" on the bottom row) - also maybe put "create new" on the top row with the "load", "save" buttons

2020-05-14 00:40 UTC, jasmine-nahrain commented
I swapped the rows. Only thing is I cant put "create new" on the top row because then the rows are very uneven. Instead I just put it at the beginning of the second row.

![image](https://user-images.githubusercontent.com/40879549/81879870-406ee600-95cf-11ea-9b76-e2fb1b93f746.png)

2020-05-14 00:50 UTC, jsaji approved these changes

2020-05-15 06:41 UTC, alexadonov approved these changes

2020-05-15 07:21 UTC, merged